### ISSUE TITLE
Support for SCL?

### ISSUE THREAD

**Issue by erik-stephens** [stankevich/puppet-python#189]
I don't see a way to use this module with a python from [SCL](https://www.softwarecollections.org).  Anyone know how, if at all, to get this to work with an SCL python?  If not, is it something you would like to support in this module?  I can work on a PR if would be useful.

**Comment by Tokynet** [comment]
BUMP :)

**Comment by shivapoudel** [comment]
@erik-stephens PR welcome :)

**Comment by sorreltree** [comment]
A few general notes on this that didn't go into the pull request.

The pyvenv module appears to insist on creating the target directory for the venv before running the pyvenv command.  This actually breaks pyvenv unless you pass in the --clear or the --update command in python 3.3.  I kludged this by putting --clear in the pyvenv command for scl, but I think it will break for non-scl installs as well.  I'd say a better solution would be to either remove target directory resource or to include --clear in the default command line.

Additionally, there doesn't seem to be any order enforced on the creation of the venv, so you can end up with puppet trying to create the venv before the desired python version is installed.  This is of course fixable with the "play it again, Sam" method (just run puppet again and it'll do it) but that isn't the nicest of solutions.  I can open these as separate issues, but I wanted to note them as issues with the build here.

Finally, because of the weird way that RH designed SCL, you still need to either run scl enable or set the environment variables by hand before activating the virtualenv, but that's a "feature" of SCL.  I've considered adding an option to modify the activate file to do that automatically (because why not?) but that's a bigger undertaking.
